name: Generate css vars from tokens and copy
on: [push]

jobs:
    build_tokens:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.0
            - run: npm install
            - run: npx token-transformer input/token_ibm.json input/ibm.json IBM --expandTypography=true --expandShadow=true --expandComposition=true --expandBorder=true
            - run: npx token-transformer input/token_ibm.json input/ibm-pink.json IBM_Pink --expandTypography=true --expandShadow=true --expandComposition=true --expandBorder=true
            - run: npx token-transformer input/token_ibm.json input/ibm-pin_cop.json IBM_Pin_Cop --expandTypography=true --expandShadow=true --expandComposition=true --expandBorder=true
            - run: npx token-transformer input/token_ibm.json input/ibm-pin.json IBM_Pin --expandTypography=true --expandShadow=true --expandComposition=true --expandBorder=true
            - run: node build.js
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: build tokens
    copy_tokens:
        runs-on: ubuntu-latest
        needs: [build_tokens]
        steps:
            - uses: andstor/copycat-action@v3.2.4
              with:
                  personal_token: ${{ secrets.GH_PAT }}
                  src_branch: main
                  src_path: output/.
                  dst_owner: maheshtalada
                  dst_repo_name: ds-token-automation-demo
                  dst_branch: main
                  dst_path: src/css/.
                  username: maheshtalada
                  email: maheshtalada@gmail.com
                  commit_message: copy css tokens
